invy/config/routes.rb
require 'constraints/authenticated'
require 'constraints/account_created'

Rails.application.routes.draw do
  
  scope module: 'user_controllers' do
    resources :account_activations, only: [:new, :create, :edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :edit, :update]
    resources :user_pages
  end
  
  scope module: 'account_controllers' do
    resources :classics
    resources :accountants
    resources :corporates
  end
  
  scope module: 'ledger_item_controllers' do
    resources :ledger_items
  end
  
  scope module: 'client_controllers' do
    resources :clients
  end
  
  
  
  constraints(Constraints::Authenticated.new) do
    #IF ACCOUNT IS CREATED
    constraints(Constraints::AccountCreated.new) do
      root 'account_pages_controllers/account_pages#account_dispatcher', as: :account_authenticated
      get 'add_account' => 'account_pages_controllers/account_pages#add'
      get 'pay' => 'ledger_item_controllers/payment#pay'
      get 'switch_classic' => 'account_pages_controllers/account_pages#switch_to_classic'
      get 'switch_corporate' => 'account_pages_controllers/account_pages#switch_to_corporate'
      get 'switch_accountant' => 'account_pages_controllers/account_pages#switch_to_accountant'
      get 'usage' => 'usage_controllers/usages#usage'
      get 'invoices' => 'my_invoices_controllers/my_invoices#invoices'
      
      scope '/classic' do
        root 'account_pages_controllers/classic_pages#dashboard', as: :classic_account
        get 'classic_usage' => 'usage_controllers/usages#show'
        
        
      end
      
      scope '/corporate' do
        root 'account_pages_controllers/corporate_pages#dashboard', as: :corporate_account
        get 'create_invoice' => 'ledger_item_controllers/ledger_items#new'
        get 'clients' => 'client_controllers/clients#index'
        get 'corporate_usage' => 'usage_controllers/usages#show'
      end
      
      scope '/accountant' do
        root 'account_pages_controllers/accountant_pages#dashboard', as: :accountant_account
      end
    end
    
    #IF ACCOUNT IS NOT YET CREATED
    root 'user_controllers/user_pages#dashboard', as: :user_authenticated
    get 'add_classic' => 'account_controllers/classics#new'
    get 'add_corporate' => 'account_controllers/corporates#new'
    get 'add_accountant' => 'account_controllers/accountants#new'
    get 'profile' => 'user_controllers/user_pages#profile'
  end
  
  
  root 'static_pages#home'
  #ACCOUNT_ACTIVATIONS CONTROLLER
  get 'resend_activation' => 'user_controllers/account_activations#new'
  #PASSWORD_RESET CONTROLLER
  get 'reset_password' => 'user_controllers/password_resets#new'
  #SESSION CONTROLLER
  get 'login' => 'user_controllers/sessions#new'
  delete 'logout' => 'user_controllers/sessions#destroy'
  #USER CONTROLLER
  get 'signup' => 'user_controllers/users#new'
  get 'verification' => 'user_controllers/users#verification'
  
  #Redirec to root if trying to access other pages
  get '*path' => redirect('/')
end

invy/app/controllers/account_pages_controllers/account_pages_controller.rb
class AccountPagesControllers::AccountPagesController < ApplicationController
  
  def add
  end
  
  def switch_to_classic
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    classic_id = accounts.where("classic_id > ?", 0).take.classic_id
    classic_account = Classic.where(id: classic_id).first
    classic_account.update_attribute(:default_account, true)
    if accounts.where("corporate_id > ?", 0).exists?
      corporate_id = accounts.where("corporate_id > ?", 0).take.corporate_id
      corporate_account = Corporate.where(id: corporate_id).first
      corporate_account.update_attribute(:default_account, false)
    end
    if accounts.where("accountant_id > ?", 0).exists?
      accountant_id = accounts.where("accountant_id > ?", 0).take.accountant_id
      accountant_account = Accountant.where(id: accountant_id).first
      accountant_account.update_attribute(:default_account, false)
    end
    redirect_to root_path
  end
  
  def switch_to_corporate
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    corporate_id = accounts.where("corporate_id > ?", 0).take.corporate_id
    corporate_account = Corporate.where(id: corporate_id).first
    corporate_account.update_attribute(:default_account, true)
    if accounts.where("classic_id > ?", 0).exists?
      classic_id = accounts.where("classic_id > ?", 0).take.classic_id
      classic_account = Classic.where(id: classic_id).first
      classic_account.update_attribute(:default_account, false)
    end
    if accounts.where("accountant_id > ?", 0).exists?
      accountant_id = accounts.where("accountant_id > ?", 0).take.accountant_id
      accountant_account = Accountant.where(id: accountant_id).first
      accountant_account.update_attribute(:default_account, false)
    end
    redirect_to root_path
  end
  
  def switch_to_accountant
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    accountant_id = accounts.where("accountant_id > ?", 0).take.accountant_id
    accountant_account = Accountant.where(id: accountant_id).first
    accountant_account.update_attribute(:default_account, true)
    if accounts.where("classic_id > ?", 0).exists?
      classic_id = accounts.where("classic_id > ?", 0).take.classic_id
      classic_account = Classic.where(id: classic_id).first
      classic_account.update_attribute(:default_account, false)
    end
    if accounts.where("corporate_id > ?", 0).exists?
      corporate_id = accounts.where("corporate_id > ?", 0).take.corporate_id
      corporate_account = Corporate.where(id: corporate_id).first
      corporate_account.update_attribute(:default_account, false)
    end
    redirect_to root_path
  end
  
  def account_dispatcher
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    accounts.each do |account|
      if account.classic_id.present? && Classic.where(id: account.classic_id).take.default_account == true
        redirect_to classic_account_path
      elsif account.corporate_id.present? && Corporate.where(id: account.corporate_id).take.default_account == true
         redirect_to corporate_account_path
      elsif account.accountant_id.present? && Accountant.where(id: account.accountant_id).take.default_account == true
        redirect_to accountant_account_path
      end
    end
  end
end

invy/app/controllers/account_pages_controllers/accountant_pages_controller.rb
class AccountPagesControllers::AccountantPagesController < ApplicationController
  
  layout 'dashboards/dashboard_accountant'
  
  def dashboard
  end
  
end

invy/app/controllers/account_pages_controllers/classic_pages_controller.rb
class AccountPagesControllers::ClassicPagesController < ApplicationController
  include SessionsHelper
  include AccountHelper
  
  layout 'dashboards/dashboard_classic'
  
  def dashboard
    @current_classic = current_classic_account.first
    
    if Rails.env.development?
      @received_ledger_list = @current_classic.ledger_items_as_receiver.order("created_at DESC").where("strftime('%m', created_at)= ?", Date.today.strftime("%m"))
    else
      @received_ledger_list = @current_classic.ledger_items_as_receiver.order("created_at DESC").where("extract(month from created_at)=?", Date.today.strftime("%m"))
    end
    
    @new_invoices_list = @received_ledger_list.where(ledger_status: "new").order("created_at DESC")
    @paid_ledger_list = @received_ledger_list.where(ledger_status: "paid").order("created_at DESC")
    @open_amount = @received_ledger_list.sum :total_with_taxes
    @paid_amount = @paid_ledger_list.sum :total_with_taxes
  end
  
  
  
end

invy/app/controllers/account_pages_controllers/corporate_pages_controller.rb
class AccountPagesControllers::CorporatePagesController < ApplicationController
  include SessionsHelper
  include AccountHelper
  
  layout 'dashboards/dashboard_corporate'
  
  def dashboard
    @current_corporate = current_corporate_account.first
    @clients_list = @current_corporate.corporate.list_clients
    @clients = Client.where(id: @clients_list.map(&:client_id))
    
    if Rails.env.development?
      @sent_ledger_list = @current_corporate.ledger_items_as_sender.where("strftime('%m', created_at)= ?", Date.today.strftime("%m")).order("created_at DESC")
      @received_ledger_list = @current_corporate.ledger_items_as_receiver.where("strftime('%m', created_at)= ?", Date.today.strftime("%m")).order("created_at DESC")
    else
      @sent_ledger_list = @current_corporate.ledger_items_as_sender.where("extract(month from created_at)=?", Date.today.strftime("%m")).order("created_at DESC")
      @received_ledger_list = @current_corporate.ledger_items_as_receiver.where("extract(month from created_at)=?", Date.today.strftime("%m")).order("created_at DESC")
    end
    
    @paid_received_ledger_list = @received_ledger_list.where(ledger_status: "paid")
    @due_amount = @sent_ledger_list.where(ledger_status: "new").sum :total_with_taxes
    @open_amount = @received_ledger_list.sum :total_with_taxes
    @paid_amount = @received_ledger_list.where(ledger_status: "paid").sum :total_with_taxes
  end
  
end

invy/app/helpers/corporate_pages_helper.rb
module CorporatePagesHelper
  
  private
  def other_accounts_than_corporate?
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    if accounts.where("classic_id > ?", 0).exists? || accounts.where("accountant_id > ?", 0).exists?
      true
    else
      false
    end
  end
  
  def classic_account?
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    if accounts.where("classic_id > ?", 0).exists?
      true
    else
      false
    end
  end
  
  def accountant_account?
    accounts = Account.where(id: current_user.user_accounts.map(&:account_id))
    if accounts.where("accountant_id > ?", 0).exists?
      true
    else
      false
    end
  end
end

invy/app/views/account_pages_controllers/corporate_pages/dashboard.html.erb
<% provide(:title, "Dashboard")%>



<div class="container">
	<div class="corporate-banner">
		<div class="row">
			<div class="col-sm-4">
				<div class="sent-invoices-info">
					<div class="sent-invoices-info-container">
						<div class="row">
							<div class="col-sm-12">
								<div class="header">
									<span class="sent-amount"><%= @sent_ledger_list.count %></span> <%= "invoice".pluralize(@sent_ledger_list.count)%> sent
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="due-amount">
									<%= number_to_currency(@due_amount, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="footer">
									currently due amount
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		
			<div class="col-sm-4">
				<div class="received-invoices-info">
					<div class="received-invoices-info-container">
						<div class="row">
							<div class="col-sm-12">
								<div class="header">
									<span class="received-amount"><%= @received_ledger_list.count %></span> <%= "invoice".pluralize(@received_ledger_list.count)%> received
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="open-amount">
									<%= number_to_currency((@open_amount), unit: "€", separator: ",", delimiter: ".", precision: 2)%>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="footer">
									currently total amount
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		
			<div class="col-sm-4">
				<div class="paid-info">
					<div class="paid-info-container">
						<div class="row">
							<div class="col-sm-12">
								<div class="header">
										<span class="paid-amount"><%= @paid_received_ledger_list.count %></span> <%= "invoice".pluralize(@paid_received_ledger_list.count)%> paid
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="paid-amount">
									<% if @paid_amount != @open_amount && @paid_amount != 0%>
										<span class="red"><%= number_to_currency(@paid_amount, unit: "€", separator: ",", delimiter: ".", precision: 2)%></span>
									<%else%>
										<%= number_to_currency(@paid_amount, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
									<%end%>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="footer">
									currently paid amount
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	
	<div class="corporate-banner received-invoices-container">
		<div class="title">
			<span class="pull-left">My received <%= "invoice".pluralize(@received_ledger_list.count)%> (<%= @received_ledger_list.count %>)</span>
			<span class="pull-right date"><%= Time.now.strftime("%B %Y")%></span>
		</div>
		
		<div class="received-invoice-table-container">
			<table class="table">
				<thead>
					<tr>
						<th>Status</th>
						<th>Reference</th>
						<th>From</th>
						<th>Date</th>
						<th>Due</th>
						<th>Amount</th>
						<th>Open</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @received_ledger_list.each do |invoice| %>
						<tr>
							<td>
								<% if invoice.ledger_status == "new" %>
									<span class="fa-stack pending-payment-icon">
										<i class="fa fa-exclamation fa-stack-1x"></i>
										<i class="fa fa-circle-o fa-stack-2x"></i>
									</span>
								<% else%>
									<span class="fa-stack paid-icon">
										<i class="fa fa-check fa-stack-1x"></i>
										<i class="fa fa-circle-o fa-stack-2x"></i>
									</span>
								<% end %>
							</td>
							<td><%= invoice.ref_number%></td>
							<td>
								<% @sender_account = Account.where(id: invoice.sender_id).first %>
								<%= @sender_account.corporate.company_name%>
							</td>
							<td><%= invoice.issue_date.strftime("%d/%m/%Y")%></td>
							<td><%= invoice.due_date.strftime("%d/%m/%Y")%></td>
							<td>
								<%= number_to_currency(invoice.total_with_taxes, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
							</td>
							<td>
								<% if invoice.ledger_status == "new"%>
									<span class="unpaid">
										<%= number_to_currency(invoice.total_with_taxes, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
									</span>
								<%else%>
									<span class="paid">
										<%= number_to_currency(0, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
									</span>
								<%end%>
							</td>
							<td>
								<%= link_to ledger_item_path(invoice) do %>
									<i class="fa fa-file-o invoice-icon" aria-hidden="true"></i>
								<%end%>
							</td>
						</tr>
					<%end%>
				</tbody>
			</table>
			
			<% if @received_ledger_list.empty? %>
				<div class="no-invoices">
					You haven't received any invoices this month yet.
				</div>
			<%end%>
			
		</div>
		<div class="footer">
			<%= link_to invoices_path do %>
				All your invoices <i class="fa fa-chevron-right" aria-hidden="true"></i>
			<%end%>
		</div>
	</div>
	
	
	<div class="corporate-banner sent-invoices-container">
		<div class="title">
			<span class="pull-left">My sent <%= "invoice".pluralize(@sent_ledger_list.count)%> (<%= @sent_ledger_list.count %>)</span>
			<span class="pull-right date"><%= Time.now.strftime("%B %Y")%></span>
		</div>
		
		<div class="sent-invoice-table-container">
			<table class="table">
				<thead>
					<tr>
						<th>Status</th>
						<th>Reference</th>
						<th>To</th>
						<th>Date</th>
						<th>Due</th>
						<th>Amount</th>
						<th>Open</th>
						<th></th>
					</tr>
				</thead>
				<% @sent_ledger_list.each do |invoice| %>
					<tr>
						<td>
							<% if invoice.ledger_status == "new" %>
								<span class="fa-stack pending-payment-icon">
									<i class="fa fa-exclamation fa-stack-1x"></i>
									<i class="fa fa-circle-o fa-stack-2x"></i>
								</span>
							<% else%>
								<span class="fa-stack paid-icon">
									<i class="fa fa-check fa-stack-1x"></i>
									<i class="fa fa-circle-o fa-stack-2x"></i>
								</span>
							<% end %>
						</td>
						<td><%= invoice.ref_number%></td>
						<td>
							<% @receiver_account = Account.where(id: invoice.receiver_id).first %>
							<% if @receiver_account['classic_id'] > 0 %>
							    <% @receiver_user_account = UserAccount.where(account_id: @receiver_account).first %>
							    <% @receiver = User.where(id: @receiver_user_account.user_id).first %>
								<%= @receiver.first_name.first %>. <%= @receiver.last_name %>
								
							<% elsif @receiver_account['corporate_id'] > 0%>
								<%= @receiver_account.corporate.company_name%>
							<%end%>
						</td>
						<td><%= invoice.issue_date.strftime("%d/%m/%Y")%></td>
						<td><%= invoice.due_date.strftime("%d/%m/%Y")%></td>
						<td>
							<%= number_to_currency(invoice.total_with_taxes, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
						</td>
						<td>
							<% if invoice.ledger_status == "new"%>
								<span class="unpaid">
									<%= number_to_currency(invoice.total_with_taxes, unit: "€", separator: ",", delimiter: ".", precision: 2)%>			
								</span>
							<% else %>
								<span class="paid">
									<%= number_to_currency(0, unit: "€", separator: ",", delimiter: ".", precision: 2)%>
								</span>
							<%end%>
						</td>
						<td>
							<%= link_to ledger_item_path(invoice) do %>
								<i class="fa fa-file-o invoice-icon" aria-hidden="true"></i>
							<%end%>
						</td>
					</tr>
				<%end%>
			</table>
				
			<% if @sent_ledger_list.empty? %>
				<div class="no-invoices">
					You haven't sent any invoices this month yet.
				</div>
			<%end%>
		</div>
		
		<div class="footer">
			<%= link_to invoices_path do %>
				All your invoices <i class="fa fa-chevron-right" aria-hidden="true"></i>
			<%end%>
		</div>
	</div>
</div>